### ISSUE TITLE
Kanban board Arrangement

### ISSUE THREAD

**Issue by M-Anwar-Hussaini** [M-Anwar-Hussaini/Space-Travelers-Hub#28]
# Task distribution and work arrangement:

- [Project source code](https://github.com/M-Anwar-Hussaini/Space-Travelers-Hub).
- [Kanban board setup](https://github.com/M-Anwar-Hussaini/Space-Travelers-Hub/projects/1).

## Authors:
- [Anwar Hussaini](https://github.com/M-Anwar-Hussaini).
- [Abdelaziz Mahdi](https://github.com/Abdelaziz-Ali).

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Please add the following card/issue to your kanban board, to match the template kanban given.
![image](https://github.com/M-Anwar-Hussaini/Space-Travelers-Hub/assets/62290545/7279b860-aae4-4e13-82b5-d40075a0d44a)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by M-Anwar-Hussaini** [comment]
Hi @ShadyShawkat. 
Thanks a lot for mentioning this point. It was removed mistakenly by us. I've now included it.

**Comment by KayLemba** [comment]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello TEAM   , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  . 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Professional Readme file 
- [x] No linter errors
- [x] Kanban Board setup correctly


 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]
